#spring:
#  application:
#    name: IMMO-SERVICE
#
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/
#  instance:
#      hostname: localhost
#      prefer-ip-address: true  
#server:
#  port: 8082